spring:
  application:
    name: ChamberReckoning
  websocket:
    stomp:
      enable-heartbeat: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: xxx
  logging:
    level:
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      org.mongodb.driver: DEBUG
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SERCRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: ${EMAIL_PASSWORD:YOUR_ACTUAL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      embedding:
        model: text-embedding-3-small
jwt:
  signerKey: xxx
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
server:
  port: 8080